import { ApiProfile, ApiRepository } from '../interface/IGitHubApi';

export const mockProfile: ApiProfile = {
  name: 'Test User',
  avatar_url: 'https://avatars.githubusercontent.com/u/123456',
  followers: 100,
  followers_url: 'https://api.github.com/users/testuser/followers',
  html_url: 'https://github.com/testuser',
  login: 'testuser',
  repos_url: 'https://api.github.com/users/testuser/repos',
  id: 123456,
  gravatar_id: '',
  url: 'https://api.github.com/users/testuser',
  following_url: '',
  gists_url: '',
  starred_url: '',
  subscriptions_url: '',
  organizations_url: '',
  events_url: '',
  received_events_url: '',
  type: 'User',
  site_admin: false,
  company: '',
  blog: '',
  location: '',
  email: '',
  hireable: true,
  bio: '',
  public_repos: 10,
  public_gists: 5,
  following: 50,
  created_at: '2020-01-01T00:00:00Z',
  updated_at: '2023-01-01T00:00:00Z',
};

export const mockRepositories: ApiRepository[] = [
  {
    id: 1,
    name: 'test-repo-1',
    full_name: 'testuser/test-repo-1',
    html_url: 'https://github.com/testuser/test-repo-1',
    description: 'A test repository',
    languages_url:
      'https://api.github.com/repos/testuser/test-repo-1/languages',
    stargazers_count: 20,
    updated_at: '2023-02-01T00:00:00Z',
    owner: {} as any,
    private: false,
    fork: false,
    url: '',
    forks_url: '',
    keys_url: '',
    collaborators_url: '',
    teams_url: '',
    hooks_url: '',
    issue_events_url: '',
    events_url: '',
    assignees_url: '',
    branches_url: '',
    tags_url: '',
    blobs_url: '',
    git_tags_url: '',
    git_refs_url: '',
    trees_url: '',
    statuses_url: '',
    stargazers_url: '',
    contributors_url: '',
    subscribers_url: '',
    subscription_url: '',
    commits_url: '',
    git_commits_url: '',
    comments_url: '',
    issue_comment_url: '',
    contents_url: '',
    compare_url: '',
    merges_url: '',
    archive_url: '',
    downloads_url: '',
    issues_url: '',
    pulls_url: '',
    milestones_url: '',
    notifications_url: '',
    labels_url: '',
    releases_url: '',
    deployments_url: '',
    created_at: '2020-01-01T00:00:00Z',
    pushed_at: '2023-02-01T00:00:00Z',
    git_url: '',
    ssh_url: '',
    clone_url: '',
    svn_url: '',
    homepage: '',
    size: 100,
    watchers_count: 5,
    language: 'TypeScript',
    has_issues: true,
    has_downloads: true,
    has_wiki: true,
    has_pages: false,
    forks_count: 2,
    open_issues_count: 1,
    forks: 2,
    open_issues: 1,
    watchers: 5,
    default_branch: 'main',
  },
  {
    id: 2,
    name: 'test-repo-2',
    full_name: 'testuser/test-repo-2',
    html_url: 'https://github.com/testuser/test-repo-2',
    description: 'Another test repository',
    languages_url:
      'https://api.github.com/repos/testuser/test-repo-2/languages',
    stargazers_count: 10,
    updated_at: '2023-01-01T00:00:00Z',
    owner: {} as any,
    private: false,
    fork: false,
    url: '',
    forks_url: '',
    keys_url: '',
    collaborators_url: '',
    teams_url: '',
    hooks_url: '',
    issue_events_url: '',
    events_url: '',
    assignees_url: '',
    branches_url: '',
    tags_url: '',
    blobs_url: '',
    git_tags_url: '',
    git_refs_url: '',
    trees_url: '',
    statuses_url: '',
    stargazers_url: '',
    contributors_url: '',
    subscribers_url: '',
    subscription_url: '',
    commits_url: '',
    git_commits_url: '',
    comments_url: '',
    issue_comment_url: '',
    contents_url: '',
    compare_url: '',
    merges_url: '',
    archive_url: '',
    downloads_url: '',
    issues_url: '',
    pulls_url: '',
    milestones_url: '',
    notifications_url: '',
    labels_url: '',
    releases_url: '',
    deployments_url: '',
    created_at: '2020-01-01T00:00:00Z',
    pushed_at: '2023-01-01T00:00:00Z',
    git_url: '',
    ssh_url: '',
    clone_url: '',
    svn_url: '',
    homepage: '',
    size: 100,
    watchers_count: 5,
    language: 'JavaScript',
    has_issues: true,
    has_downloads: true,
    has_wiki: true,
    has_pages: false,
    forks_count: 2,
    open_issues_count: 1,
    forks: 2,
    open_issues: 1,
    watchers: 5,
    default_branch: 'main',
  },
];

export const mockLanguageStats = [
  { TypeScript: 1000, JavaScript: 500 },
  { Python: 800, TypeScript: 200 },
];

/**
 * Creates a mock repository with custom properties
 */
export function createMockRepository(
  overrides: Partial<ApiRepository> = {},
): ApiRepository {
  return {
    ...mockRepositories[0],
    ...overrides,
  };
}

/**
 * Creates a mock profile with custom properties
 */
export function createMockProfile(
  overrides: Partial<ApiProfile> = {},
): ApiProfile {
  return {
    ...mockProfile,
    ...overrides,
  };
}
